commit_hash = { ASCII_HEX_DIGIT{40} }
commit_title = { (ASCII_ALPHANUMERIC | "@" | "-" | "_" | "/" | ":" | " " | "!" | "(" | ")" | "#")+ }
git_commit = {commit_hash ~ WHITE_SPACE ~ commit_title ~ NEWLINE}

branch_tag = _{ "->" }
origin = { ASCII_ALPHANUMERIC+ }
branch_name = { (ASCII_ALPHANUMERIC | "@" | "-" | "_" | "/")+ }
target = { branch_tag ~ WHITE_SPACE* ~ (origin ~ ":")? ~ branch_name ~ NEWLINE}

commit = {
    git_commit ~ (target ~ NEWLINE*){, 1} ~ NEWLINE*
}

commits = { commit+ }
