string = _{ (!NEWLINE ~ ANY)+ }

commit_hash = { ASCII_HEX_DIGIT{40} }
commit_title = { string }
git_commit = {commit_hash ~ WHITE_SPACE ~ commit_title ~ NEWLINE}


branch_tag = _{ "->" }
branch_name = { string }
target = { branch_tag ~ WHITE_SPACE* ~ branch_name ~ NEWLINE}

test_tag = { "$" }
command = { string }
test = { test_tag ~ WHITE_SPACE+ ~ command ~ NEWLINE }

commit = {
    git_commit ~ (target ~ NEWLINE*){, 1} ~ test* ~ NEWLINE*
}

commits = { commit+ }
