[package]
name = "yggit-db"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = "3"
