name: Merge Request
run-name: Testing if mergeable
on:
  pull_request:
    branches:
      - main
    paths:
      - editor/**
      - crates/**
      - Cargo.lock
      - Cargo.toml
      - clippy.toml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run formatter
        run: |
          rustup component add rustfmt
          cargo fmt
      - name: Run linter
        run: cargo clippy
      - name: Audit
        run: |
          cargo install cargo-audit
          cargo audit --deny warnings
      - name: Check for useless dependencies
        run: |
          cargo install cargo-machete
          cargo machete
      - name: Run tests
        run: cargo test
      - name: Build the project
        run: cargo build --release